export const DEMO_SUPPLIERS = [
  {
    id: "d3b07384-d113-4696-a94f-01584c3c3a01",
    supplier_code: "SUP-1001",
    legal_name: "Global Chip Dynamics Inc.",
    dba_name: "Global Chip Dynamics",
    category: "Semiconductors",
    company_type: "Corporation",
    status: "Active",
    city: "San Jose",
    state: "CA",
    country: "USA",
    contact_name: "Alice Chen",
    contact_email: "alice@globalchip.com",
    contact_phone: "+1 (408) 555-0192",
    website: "https://globalchipdynamics.example.com",
    payment_terms: "Net 30",
    currency: "USD",
    diverse_supplier: false,
    news_cadence: "Weekly",
    alerts_enabled: true,
    riskAlerts: []
  },
  {
    id: "e4c18495-e224-5707-b05e-12695d4d4b02",
    supplier_code: "SUP-1002",
    legal_name: "Nexus Logistics Group LLC",
    dba_name: "Nexus Logistics",
    category: "Logistics & Freight",
    company_type: "LLC",
    status: "Active",
    city: "Dallas",
    state: "TX",
    country: "USA",
    contact_name: "Marcus Vance",
    contact_email: "marcus@nexuslogistics.com",
    contact_phone: "+1 (214) 555-0148",
    website: "https://nexuslogistics.example.com",
    payment_terms: "Net 60",
    currency: "USD",
    diverse_supplier: true,
    news_cadence: "Daily",
    alerts_enabled: true,
    riskAlerts: [
      {
        id: "a1a1a1a1-1111-2222-3333-444444444444",
        supplier_id: "e4c18495-e224-5707-b05e-12695d4d4b02",
        event_type: "Supply Disruption",
        severity: "High",
        title: "Port Congestion Delay",
        detail: "Shipments delayed by 14 days due to West Coast labor bottleneck.",
        status: "NEW",
        created_at: new Date().toISOString()
      }
    ]
  },
  {
    id: "f5d29506-f335-6818-c16f-23706e5e5c03",
    supplier_code: "SUP-1003",
    legal_name: "Apex Precision Sensors Ltd.",
    dba_name: "Apex Sensors",
    category: "Electronics",
    company_type: "Corporation",
    status: "Active",
    city: "Austin",
    state: "TX",
    country: "USA",
    contact_name: "Elena Rostova",
    contact_email: "elena@apexsensors.com",
    contact_phone: "+1 (512) 555-0183",
    website: "https://apexsensors.example.com",
    payment_terms: "Net 45",
    currency: "USD",
    diverse_supplier: false,
    news_cadence: "Weekly",
    alerts_enabled: true,
    riskAlerts: []
  }
];
